name: bangladesh_agro_marketplace
description: Agricultural marketplace prototype for Bangladesh

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # Image Handling
  image_picker: ^1.0.4
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # HTTP requests (for future backend)
  http: ^1.1.0
  
  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true